name: meet_network_image
description: A flutter package for showing Image from Url with LoadingBuilder and ErrorBuilder.
version: 0.1.3
author: Onat Cipli<ciplionat35@gmail.com>
homepage: https://github.com/onatcipli/meet_network_image

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
